<?php
/**
 * GENERATED by tools/derive-dump-preamble.sh from a real mysqldump. DO NOT EDIT BY HAND.
 *
 * Re-derive with:   tools/derive-dump-preamble.sh --via-ssh cp1-kapsule
 * Verified in CI by: tools/verify-dump-preamble.sh
 *
 * These are the session statements a real mysqldump wraps its output in. The plugin's own
 * writer emitted none of them, so an imported site could arrive with its timestamps shifted by
 * the destination's UTC offset and its four-byte characters rejected outright.
 */

class Kapsule_Dump_Preamble {

    public static function preamble(): string {
        return implode( "\n", array(
            '/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;',
            '/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;',
            '/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;',
            '/*!40101 SET NAMES utf8mb4 */;',
            '/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;',
            '/*!40103 SET TIME_ZONE=\'+00:00\' */;',
            '/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;',
            '/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;',
            '/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=\'NO_AUTO_VALUE_ON_ZERO\' */;',
            '/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;',
        ) ) . "\n";
    }

    public static function epilogue(): string {
        return implode( "\n", array(
            '/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;',
            '/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;',
            '/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;',
            '/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;',
            '/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;',
            '/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;',
            '/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;',
            '/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;',
        ) ) . "\n";
    }
}
